// Built-in particle-generator presets. Each is a single `particle` scene node
// whose tuned config lives in the `components.particle` bag (merged against
// PARTICLE_DEFAULTS on the frontend, so only non-default fields are listed).
import {
  sceneNode,
  sceneNodePreset,
  transform,
  type BuiltinPreset,
} from './helpers.js';

function particlePreset(
  id: string,
  name: string,
  description: string,
  nodeName: string,
  pos: [number, number, number],
  particle: Record<string, unknown>
): BuiltinPreset {
  return sceneNodePreset(id, name, description, [
    sceneNode('n1', null, nodeName, 'particle', {
      transform: transform(pos[0], pos[1], pos[2]),
      particle,
    }),
  ]);
}

export const PARTICLE_PRESETS: BuiltinPreset[] = [
  particlePreset(
    'builtin:particles-rain',
    'Rain',
    'Falling rain — fast vertical streaks over a wide area.',
    'Rain',
    [0, 5, 0],
    {
      blendMode: 'normal',
      colorStart: '#9bb8d8',
      colorEnd: '#7a98b8',
      alpha: 0.55,
      alphaOverLifetime: 'constant',
      maxCount: 800,
      emissionRate: 300,
      lifetime: 1.2,
      lifetimeRandom: 0.2,
      sizeX: 0.012,
      sizeY: 0.18,
      sizeRandomX: 0.2,
      sizeRandomY: 0.3,
      sizeOverLifetime: 'constant',
      directionX: 0,
      directionY: -1,
      directionZ: 0,
      spread: 2,
      speed: 8,
      speedRandom: 0.2,
      originW: 4,
      originH: 0,
      originD: 4,
      gravityX: 0,
      gravityY: -4,
      gravityZ: 0,
      rotationMode: 'velocity',
      rotationStart: 0,
    }
  ),
  particlePreset(
    'builtin:particles-snow',
    'Snow',
    'Gently drifting snowflakes with turbulent sway.',
    'Snow',
    [0, 5, 0],
    {
      blendMode: 'normal',
      colorStart: '#ffffff',
      colorEnd: '#ffffff',
      alpha: 0.9,
      alphaOverLifetime: 'fade-out',
      maxCount: 500,
      emissionRate: 80,
      lifetime: 5,
      lifetimeRandom: 0.3,
      sizeX: 0.04,
      sizeY: 0.04,
      sizeRandomX: 0.5,
      sizeRandomY: 0.5,
      sizeOverLifetime: 'constant',
      directionX: 0,
      directionY: -1,
      directionZ: 0,
      spread: 25,
      speed: 0.6,
      speedRandom: 0.5,
      originW: 4,
      originH: 0,
      originD: 4,
      gravityX: 0,
      gravityY: -0.2,
      gravityZ: 0,
      turbulence: 0.6,
      rotationMode: 'free',
      rotationStart: 180,
      angularVelocity: 30,
      angularVelocityRandom: 1,
    }
  ),
  particlePreset(
    'builtin:particles-fire',
    'Fire',
    'Rising flames — additive, fading from yellow to red.',
    'Fire',
    [0, 0, 0],
    {
      blendMode: 'additive',
      colorStart: '#ffd23a',
      colorEnd: '#ff2a00',
      alpha: 0.85,
      alphaOverLifetime: 'fade-out',
      maxCount: 300,
      emissionRate: 120,
      lifetime: 1,
      lifetimeRandom: 0.3,
      sizeX: 0.25,
      sizeY: 0.25,
      sizeRandomX: 0.4,
      sizeRandomY: 0.4,
      sizeOverLifetime: 'shrink',
      directionX: 0,
      directionY: 1,
      directionZ: 0,
      spread: 18,
      speed: 1.2,
      speedRandom: 0.5,
      originW: 0.15,
      originH: 0,
      originD: 0.15,
      gravityX: 0,
      gravityY: 0.4,
      gravityZ: 0,
      turbulence: 0.4,
      rotationMode: 'free',
      rotationStart: 180,
    }
  ),
  particlePreset(
    'builtin:particles-magic-sparkles',
    'Magic Sparkles',
    'Slow drifting magical motes — pulsing, glowing, multicoloured.',
    'Magic Sparkles',
    [0, 1, 0],
    {
      blendMode: 'additive',
      colorStart: '#b98cff',
      colorEnd: '#52e0ff',
      alpha: 1,
      alphaOverLifetime: 'fade-in-out',
      maxCount: 250,
      emissionRate: 60,
      lifetime: 1.8,
      lifetimeRandom: 0.4,
      sizeX: 0.06,
      sizeY: 0.06,
      sizeRandomX: 0.6,
      sizeRandomY: 0.6,
      sizeOverLifetime: 'pulse',
      directionX: 0,
      directionY: 1,
      directionZ: 0,
      spread: 80,
      speed: 0.5,
      speedRandom: 0.8,
      originW: 0.4,
      originH: 0.4,
      originD: 0.4,
      gravityX: 0,
      gravityY: 0.1,
      gravityZ: 0,
      turbulence: 0.8,
      rotationMode: 'free',
      rotationStart: 180,
      angularVelocity: 120,
      angularVelocityRandom: 1,
    }
  ),
  particlePreset(
    'builtin:particles-sparkler',
    'Sparkler',
    'Handheld sparkler — bright sparks burst out in all directions and arc down.',
    'Sparkler',
    [0, 1, 0],
    {
      blendMode: 'additive',
      colorStart: '#fffbe0',
      colorEnd: '#ff7b00',
      alpha: 1,
      alphaOverLifetime: 'fade-out',
      maxCount: 500,
      emissionRate: 350,
      lifetime: 0.5,
      lifetimeRandom: 0.6,
      sizeX: 0.015,
      sizeY: 0.05,
      sizeRandomX: 0.6,
      sizeRandomY: 0.6,
      sizeOverLifetime: 'shrink',
      directionX: 0,
      directionY: 1,
      directionZ: 0,
      spread: 180,
      speed: 3,
      speedRandom: 0.7,
      originW: 0.02,
      originH: 0.02,
      originD: 0.02,
      gravityX: 0,
      gravityY: -2.5,
      gravityZ: 0,
      turbulence: 0.3,
      rotationMode: 'velocity',
      rotationStart: 0,
    }
  ),
];
