// ──────────────────────────────────────────────────────────────────────────────
// ARKit 52 shape names — RhyLive /Face message order (Apple's canonical order)
// ──────────────────────────────────────────────────────────────────────────────

// Apple LiveLink / RhyLive sends ARKit blendshapes in strict alphabetical order.
export const ARKIT_SHAPES = [
  'browDownLeft',
  'browDownRight',
  'browInnerUp',
  'browOuterUpLeft',
  'browOuterUpRight',
  'cheekPuff',
  'cheekSquintLeft',
  'cheekSquintRight',
  'eyeBlinkLeft',
  'eyeBlinkRight',
  'eyeLookDownLeft',
  'eyeLookDownRight',
  'eyeLookInLeft',
  'eyeLookInRight',
  'eyeLookOutLeft',
  'eyeLookOutRight',
  'eyeLookUpLeft',
  'eyeLookUpRight',
  'eyeSquintLeft',
  'eyeSquintRight',
  'eyeWideLeft',
  'eyeWideRight',
  'jawForward',
  'jawLeft',
  'jawOpen',
  'jawRight',
  'mouthClose',
  'mouthDimpleLeft',
  'mouthDimpleRight',
  'mouthFrownLeft',
  'mouthFrownRight',
  'mouthFunnel',
  'mouthLeft',
  'mouthLowerDownLeft',
  'mouthLowerDownRight',
  'mouthPressLeft',
  'mouthPressRight',
  'mouthPucker',
  'mouthRight',
  'mouthRollLower',
  'mouthRollUpper',
  'mouthShrugLower',
  'mouthShrugUpper',
  'mouthSmileLeft',
  'mouthSmileRight',
  'mouthStretchLeft',
  'mouthStretchRight',
  'mouthUpperUpLeft',
  'mouthUpperUpRight',
  'noseSneerLeft',
  'noseSneerRight',
  'tongueOut',
] as const;

export type ArkitShape = (typeof ARKIT_SHAPES)[number];
export type ArkitMapping = Partial<Record<string, [string, number][]>>;

// ── ARKit → VRM expressions ───────────────────────────────────────────────────

export const ARKIT_TO_VRM: ArkitMapping = {
  eyeWideLeft: [['surprised', 0.2]],
  eyeWideRight: [['surprised', 0.2]],
  mouthSmileLeft: [['happy', 0.3]],
  mouthSmileRight: [['happy', 0.3]],
  mouthFrownLeft: [['sad', 0.5]],
  mouthFrownRight: [['sad', 0.5]],
  browInnerUp: [['surprised', 0.6]],
  browOuterUpLeft: [['surprised', 0.2]],
  browOuterUpRight: [['surprised', 0.2]],
  browDownLeft: [['angry', 0.5]],
  browDownRight: [['angry', 0.5]],
  noseSneerLeft: [['angry', 0.25]],
  noseSneerRight: [['angry', 0.25]],
  cheekSquintLeft: [['relaxed', 0.4]],
  cheekSquintRight: [['relaxed', 0.4]],
};

// ── ARKit → VRoid Fcl_* morph targets ────────────────────────────────────────

export const ARKIT_TO_FCL: ArkitMapping = {
  eyeBlinkLeft: [['Fcl_EYE_Close_L', 1.0]],
  eyeBlinkRight: [['Fcl_EYE_Close_R', 1.0]],
  eyeSquintLeft: [['Fcl_EYE_Close_L', 0.3]],
  eyeSquintRight: [['Fcl_EYE_Close_R', 0.3]],
  eyeWideLeft: [['Fcl_EYE_Spread', 0.5]],
  eyeWideRight: [['Fcl_EYE_Spread', 0.5]],
  jawOpen: [['Fcl_MTH_A', 1.0]],
  mouthClose: [['Fcl_MTH_A', -0.8]],
  mouthPucker: [['Fcl_MTH_U', 0.9]],
  mouthFunnel: [['Fcl_MTH_O', 0.8]],
  mouthStretchLeft: [['Fcl_MTH_I', 0.5]],
  mouthStretchRight: [['Fcl_MTH_I', 0.5]],
  mouthLowerDownLeft: [['Fcl_MTH_E', 0.3]],
  mouthLowerDownRight: [['Fcl_MTH_E', 0.3]],
  mouthUpperUpLeft: [['Fcl_MTH_E', 0.2]],
  mouthUpperUpRight: [['Fcl_MTH_E', 0.2]],
  mouthSmileLeft: [['Fcl_MTH_Joy', 0.0]],
  mouthSmileRight: [['Fcl_MTH_Joy', 0.0]],
  mouthFrownLeft: [['Fcl_MTH_Sorrow', 0.5]],
  mouthFrownRight: [['Fcl_MTH_Sorrow', 0.5]],
  browDownLeft: [['Fcl_BRW_Angry', 0.5]],
  browDownRight: [['Fcl_BRW_Angry', 0.5]],
  browInnerUp: [['Fcl_BRW_Surprised', 0.6]],
  browOuterUpLeft: [['Fcl_BRW_Surprised', 0.2]],
  browOuterUpRight: [['Fcl_BRW_Surprised', 0.2]],
  noseSneerLeft: [['Fcl_BRW_Angry', 0.0]],
  noseSneerRight: [['Fcl_BRW_Angry', 0.0]],
  cheekSquintLeft: [['Fcl_EYE_Joy_L', 0.3]],
  cheekSquintRight: [['Fcl_EYE_Joy_R', 0.3]],
};
